force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs gathered from across the platform</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{YY}{MM}{DD}-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Slack_Config__mdt/Slack_Config__mdt.object-meta.xml
<CustomObject>
    <label>Slack Config</label>
    <pluralLabel>Slack Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Slack_Config__mdt/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SlackUtil.cls
public without sharing class SlackUtil {
    
    public static String SlackURL(){
        List<Slack_Config__mdt> slackURL = [
            SELECT Id, URL__c
            FROM Slack_Config__mdt
        ];
        if(slackURL.size() > 0){
            return slackURL[0].URL__c;
        } else {
            return '';
        }
    }

    public static void pushToSlack(List<Log__c> messages){
        String url = SlackURL();
        for(Log__c log : messages){
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('text', formatBody(log));
            gen.writeEndObject();

            String body = gen.getAsString();
            System.debug(body);
            System.enqueueJob(new SlackPostQueueable(url, 'POST', body));
        }
    }

    private static String formatBody(Log__c log){
        String body = '';

        body += 'Message - ' + log.Message__c;
        body += '\n';
        body += 'Exception Message - ' + log.Exception_Message__c;
        body += '\n';
        body += 'ID of Log - ' + log.Id;
        body += '\n';
        body += 'Stack Trace - ' + log.Stack_Trace__c;
        return body;
    }

}