force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Logs gathered from across the platform</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{YY}{MM}{DD}-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Exception_Cause__c.field-meta.xml
<CustomField>
    <fullName>Exception_Cause__c</fullName>
    <label>Exception Cause</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Exception_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Exception_Line_Number__c</fullName>
    <label>Exception Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Exception_Message__c.field-meta.xml
<CustomField>
    <fullName>Exception_Message__c</fullName>
    <label>Exception Message</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Exception_Stack__c.field-meta.xml
<CustomField>
    <fullName>Exception_Stack__c</fullName>
    <label>Exception Stack</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NONE</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINER</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Log__c/fields/Log_Number__c.field-meta.xml
<CustomField>
    <fullName>Log_Number__c</fullName>
    <inlineHelpText>Incremented for each log generated during a request to ensure orderability</inlineHelpText>
    <label>Log Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Record_Context__c.field-meta.xml
<CustomField>
    <fullName>Record_Context__c</fullName>
    <inlineHelpText>If log was generated while working with a record, identify that record here.</inlineHelpText>
    <label>Record Context</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Transaction_Limits__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Limits__c</fullName>
    <label>Transaction Limits</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <description>Logs published from across the system.</description>
    <label>Logs Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/default/classes/LogEventTriggerHandler.cls
public with sharing class LogEventTriggerHandler {

    public static List<Log.LogWrapper> listLogWrapper = new List<Log.LogWrapper>();

    public static void processLogEvents(){
        List<Log__c> logs = new List<Log__c>();
        for(SObject l : Trigger.new){
            logs.add(buildLog((Log_Event__e)l));
        }
        insert logs;
        SlackUtil.pushToSlack(logs);
    }

    private static Log__c buildLog(Log_Event__e e){
        Log__c log = new Log__c();

        Log.LogWrapper wrapper = (Log.LogWrapper) JSON.deserialize(e.Payload__c, Log.LogWrapper.class);
        //listLogWrapper.add(wrapper);
        log.User_Id__c = wrapper.currentUserId;
        log.Class_Name__c = wrapper.className;
        log.Method_Name__c = wrapper.methodName;
        log.Line_Number__c = Double.valueOf(wrapper.lineNum);
        log.Timestamp__c = Datetime.newInstance(wrapper.timestamp);
        log.Log_Number__c = wrapper.logNumber;
        log.Transaction_Limits__c = JSON.serialize(wrapper.transactionLimits);
        log.Exception_Type__c = wrapper.exceptionType;
        log.Exception_Message__c = wrapper.exceptionMessage;
        log.Exception_Cause__c = wrapper.exceptionCause;
        log.Exception_Line_Number__c = wrapper.exceptionLineNumber;
        log.Exception_Stack__c = wrapper.exceptionStack;
        log.Message__c = wrapper.message;
        log.Details__c = wrapper.details;
        log.Record_Context__c = wrapper.recordContext;
        log.Log_Level__c = wrapper.logLevel;
        log.Stack_Trace__c = wrapper.stackTrace;
        return log;
    }


    public LogEventTriggerHandler() {

    }
}